### ISSUE TITLE
Add support for dart null safety

### ISSUE THREAD

**Issue by Gopalkrishanbairagi** [ayvazj/flutter_lwa#4]

**Comment by Gopalkrishanbairagi** [comment]
Is there any progress regarding the issue!

**Comment by ayvazj** [comment]
If the issue is urgent please submit a pull request.  Thanks.

**Comment by ayvazj** [comment]
Thanks for the pull request. I included some additional re-factoring to eliminate nulls and published version 1.0.0. Let me know if you spot any problems.

**Comment by Gopalkrishanbairagi** [comment]
Thank you @ayvazj

**Comment by biklas7** [comment]
@ayvazj @Gopalkrishanbairagi The package isn't null safe yet right? Any progress regarding that?

**Comment by ayvazj** [comment]
@biklas7 1.0.9 should be null safe
