### ISSUE TITLE
Stuck in the browser

### ISSUE THREAD

**Issue by pkphone** [ayvazj/flutter_lwa#6]
There is no redirect back to the app after successful sign-in in amazon login from the browser. Thanks.
![218228639_202865525003112_5207907923916984449_n](https://user-images.githubusercontent.com/6669668/126857014-46d72d70-4077-4ffe-8696-0e877a509871.jpg)

**Comment by ayvazj** [comment]
Is this screen shot from the example app?  Can you include your development environment and your phone OS and model.

**Comment by pkphone** [comment]
It is not from the example app.

* Development environment:
- macOS Big Sur
- VS Code (version 1.58.2)
- Flutter (Channel stable, 2.2.3)
- Android SDK version 30.0.3

* Phone OS and model
- Android version 10
- Xiaomi MI MAX 3

**Comment by ayvazj** [comment]
Does the example app work?  Remember to update to use your API key

**Comment by pkphone** [comment]
I will check the example app. Thanks.
