### ISSUE TITLE
FATAL EXCEPTION: AmazonAuthorzationLibrary#1 IllegalArgumentException

### ISSUE THREAD

**Issue by shreya-prajapati** [ayvazj/flutter_lwa#7]
Hello,

I have integrated this library with debug mode in flutter, its working fine but having an issue with release mode of build,
Giving an error as below,
` E/AndroidRuntime(16200): FATAL EXCEPTION: AmazonAuthorzationLibrary#1
[        ] E/AndroidRuntime(16200): Process: com.onguardian.app, PID: 16200
[        ] E/AndroidRuntime(16200): java.lang.IllegalArgumentException: No serializer found for class b.a.a.a.a.l.c.e and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
[        ] E/AndroidRuntime(16200): 	at b.b.a.c.s.b(Unknown Source:111)
[        ] E/AndroidRuntime(16200): 	at b.b.a.c.s.h(Unknown Source:10)
[        ] E/AndroidRuntime(16200): 	at b.c.a.a.b$b.g(Unknown Source:8)
[        ] E/AndroidRuntime(16200): 	at b.c.a.a.b$b.a(Unknown Source:2)
[        ] E/AndroidRuntime(16200): 	at b.a.a.a.a.l.c.b$b.b(Unknown Source:7)
[        ] E/AndroidRuntime(16200): 	at b.a.a.a.a.v.a$a.b(Unknown Source:4)
[        ] E/AndroidRuntime(16200): 	at b.a.a.a.a.v.c.b(Unknown Source:36)
[        ] E/AndroidRuntime(16200): 	at b.a.a.a.a.n.i$b$a.b(Unknown Source:4)
[        ] E/AndroidRuntime(16200): 	at b.a.a.a.a.n.s.c(Unknown Source:118)
[        ] E/AndroidRuntime(16200): 	at b.a.a.a.a.n.i$b.run(Unknown Source:67)
[        ] E/AndroidRuntime(16200): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] E/AndroidRuntime(16200): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] E/AndroidRuntime(16200): 	at java.lang.Thread.run(Thread.java:923)
[        ] E/AndroidRuntime(16200): Caused by: b.b.a.c.l: No serializer found for class b.a.a.a.a.l.c.e and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
[        ] E/AndroidRuntime(16200): 	at b.b.a.c.h0.s.o.o(Unknown Source:32)
[        ] E/AndroidRuntime(16200): 	at b.b.a.c.h0.s.o.f(Unknown Source:8)
[        ] E/AndroidRuntime(16200): 	at b.b.a.c.h0.j.S(Unknown Source:73)
[        ] E/AndroidRuntime(16200): 	at b.b.a.c.s.b(Unknown Source:45)
[        ] E/AndroidRuntime(16200): 	... 12 more`

**Comment by ayvazj** [comment]
Is this happening with the example app?  Is your API key valid?

**Comment by shreya-prajapati** [comment]
Thanks for reply.

I had try with some release configuration and its working now 👍

**Comment by Moh-Snoussi** [comment]
> Thanks for reply.
> 
> I had try with some release configuration and its working now 👍

can you please share what configuration you tryed. because I am having same issue.
