### ISSUE TITLE
After releasing app in Play Store, getting 'invalid_key' error

### ISSUE THREAD

**Issue by shreya-prajapati** [ayvazj/flutter_lwa#8]
Hello,

I have implemented it in flutter and working fine for both natively Android (Debug) & iOS (Release & Debug), 

For Android Release build, facing an issue of "invalid_key" with Android Release Build,

Steps I have followed for release mode,
1) Created release keystore
2) created api_key with this keystore
3) created release build apk with new api_key in path '{project_root}/android/app/main/assets/api_key.txt' (Its working fine with LWA)
4) created release app bundle and uploaded it on Google Play Store (Giving an error 'invalid_key')

When releasing using Android App Bundles, need to sign your app bundle with an upload key before uploading it to the Play Console, and Play App Signing takes care of the rest,

I have cross verified that both key have same signature, than what's going wrong with the Released App :(

Thanks

**Comment by ayvazj** [comment]
Can you post a stack trace or error, it seems unlikely that the google play console would reject an `invalid_key` from LWA
