### ISSUE TITLE
Additional Scopes not working

### ISSUE THREAD

**Issue by PaulSocha** [ayvazj/flutter_lwa#9]
Hi, 

Trying to implement plugin for a new application using Flutter. Running into a blocker with LWA and additional scopes. Does this plugin allow for additional scopes to be added? 

I have been trying to create a solution for this, but I have not been successful.

**Comment by SimonH-Zuma** [comment]
Hi @PaulSocha. Did you find a resolution to this issue? I am attemption to use 'alexa:all' scope and get a error message on the Amazon web pages.

I'm also trying to pass a code verifier and code challenge based on the information provided here
https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/authorize-companion-app.html

**Comment by ayvazj** [comment]
Scopes are supported - but the linked alexa example requires more changes - I'll take a look at updating the example and API to support it.

**Comment by PaulSocha** [comment]
Thank you!

**Comment by ayvazj** [comment]
@PaulSocha  @SimonH-Zuma  - #10 adds support for additional arguments needed to call AVS APIs, and the example includes how to invoke it.  I will publish the package to pub.dev tomorrow, but posting the code here if you want to get an early preview.
